### ISSUE TITLE
Add resources from Awesome Transit repo

### ISSUE THREAD

**Issue by kellytdunn** [APA-Technology-Division/planning-technology-resources#11]
The Center for Urban Transportation Research runs a pretty good repo specific to transit resources: https://github.com/CUTR-at-USF/awesome-transit. There might be some good tools here to bring into this list which could be a good task for somebody. I am going to add a few myself.

**Comment by d-wasserman** [comment]
We do link to their repo here: https://github.com/APA-Technology-Division/planning-technology-resources/blob/master/resource_pages/OtherResources.md
That said, I feel some of the big ones warrant addition here! Thank you!
