### ISSUE TITLE
Alphabetical Order & Contribution Scope

### ISSUE THREAD

**Issue by c-goodman** [APA-Technology-Division/planning-technology-resources#7]
Should the resource pages, and content within them, be ordered alphabetically? This might also coincide with a rule for contributions to be ordered as such.

**Comment by d-wasserman** [comment]
This is a good question. How things are ordered and frankly even how much "detail" we need beyond a name, description, and link are all up for debate. I was thinking at least the **top level** categories should be. Happy to take a PR for better organization. 

Other hierarchies include "scale" of the datasets (international/national/state/province resources).

**Comment by c-goodman** [comment]
That's a good point, adding unnecessary rules/detail could just bog things down.

And I agree the geographic scale is important but leaving it optional makes one it easier to contribute.

By the acronym PR you mean Pull Release correct? I'm new to GitHub so still picking up on the slang. And given the beginner slant of this repository, perhaps a "Meta Resources" category is needed? It could have stuff like the [Git Cheatsheet](https://training.github.com/downloads/github-git-cheat-sheet.pdf) or [Glossary](https://docs.github.com/en/github/getting-started-with-github/github-glossary). One of the questions in the Ohio APA planning webcast one of the questions was about resources for learning about Git. And there's no replacement for interactive practice, like what this repository allows, but having some container with the best practices/GitHub Meta could be useful for first-timers. Not sure if it would nest inside "Other Resources" or be present at the top level. The balance of clutter with access is difficult.

How would you manage the "scope" of a dataset? My gut says to just use the description. For instance, I was planning on contributing the [Google Earth Engine Data Catalog](https://developers.google.com/earth-engine/datasets) at some point but it's more of a clearinghouse and there are datasets on there that might be more individually interesting like the [NLCD Image Collection.](https://developers.google.com/earth-engine/datasets/catalog/USGS_NLCD_RELEASES_2016_REL?hl=en) which could perhaps be its own thing.

Should I have made those questions separate issues? When a new issue comes up in an issue thread is it good practice to make a new issue and cite the previous thread somehow?

**Comment by d-wasserman** [comment]
All good points. I meant a Pull Request, but yes! We do need a place to put information about how to use Git/GitHub. 
Currently, this is the [spot](https://github.com/APA-Technology-Division/planning-technology-resources/blob/master/CONTRIBUTING.md) I started for that (linking to the YouTube video). We need to link to other resources such as the ones you presented. 

Good question. Clearing houses might need a geographic label that says something like "Global Clearing House", but maybe they need their own area to drop into under open data. Open Data portals have the same taxonomy problem. Using the description for now, but making clear it is a clearing house or a larger resource is a good idea.

**Comment by d-wasserman** [comment]
@lianplass , per our conversation, can you take on Alphabetizing the top level headers in each category? I think the only thing I want to change for one of them is "JS and Web" to "Web and JS". I feel like Python & R are going to be of more interest to planners generally.

**Comment by lianplass** [comment]
On it this PM. 👌  
Actually--You've reminded me that I need to send in bootstrap, chart.js and leaflet!  Those are planning website building/data vis essentials!

**Comment by d-wasserman** [comment]
This is largely addressed with #22. I think I am curious which libraries and tools we should document. It is possible awesome-js has what most people need, but we might put that under a new issue.

**Comment by lianplass** [comment]
It did occur to me that including every resource contributors came up with would cause this list to become awfully long but filtering all duplicates with other awesome lists wouldn't leave the repo with much content at all. I wonder to what extent overlap between awesome lists is permissible.  Should duplicate resources under each category be removed after exceeding a certain threshold?  If so, what is the threshold (e.g., max 5 duplicates, or may 20 resources)? Should it be removed after exceeding a set number of resources for a category?  What about a set number of similar resources per category?

**Comment by d-wasserman** [comment]
I agree. I generally think we need to be VERY selective above duplicates. I don't have any hard and fast rules to propose yet. Questions we should ask:

- What are things that planners might want to explore starting out doing web apps? 
- Is this represented in another awesome-list? Is it in our repo?
- Relative to other content, how likely would a planner reading this find it a good use of time?
- Is the item specifically targeting urban planning professionals?

**Comment by lianplass** [comment]
Greetings, David. I fully agree with this.  Would it be helpful for me to create a flowchart for contributors based on this? It seems like it might be hard to (at least initially) create hard and fast rules, but I think it would be helpful to people who are new to GitHub or interesting in developing this resource.

**Comment by d-wasserman** [comment]
Yes! That might be a good PNG to add in the contribution page under a new header.

**Comment by lianplass** [comment]
Cooked this up during my lunch break--thoughts?
![flowchart-01](https://user-images.githubusercontent.com/54779774/119541058-23c9ca00-bd5c-11eb-9ef3-c0339c15f43a.png)

**Comment by rpnathansonstl** [comment]
This is awesome.  What a productive lunch, Lian!

Couple questions:

  1.  Can we add a little bubble in the corner that gives some definitions.  There are still a lot of planners who would benefit from these resources but for whom the tech terminology is still new. (Repo/repository, contribution, Github…)



  1.  Can we share this on other channels? (socials, APA Tech Div website)


Thanks.
Rebecca

From: lianplass ***@***.***>
Date: Tuesday, May 25, 2021 at 12:22 PM
To: APA-Technology-Division/planning-technology-resources ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [APA-Technology-Division/planning-technology-resources] Alphabetical Order & Contribution Scope (#7)

Cooked this up during my lunch break--thoughts?
[flowchart-01]<https://user-images.githubusercontent.com/54779774/119541058-23c9ca00-bd5c-11eb-9ef3-c0339c15f43a.png>

**Comment by d-wasserman** [comment]
This is incredible. I think also we need the flow chart to indicate better options for "Yes" at the end. Like maybe can file an issue with a general question. I think we want to try to "Duplicate" strategically. The end bubble after yes. "File an Issue or PR and give a sentence description on why this is a strategic duplicate."
Awesome-GIS might have resources related to some of the datasets or tools we talk about here, but some are definitely some

**Comment by lianplass** [comment]
Glad to read this was well-received.  

@rpnathansonstl - I'll include definitions for the following:
 "Repository/Repo", "awesome-list", "Pull Request", "Google Docs" let me know if you think any other words might be relevant (not too many, though--that might make the flowchart seem a bit overwhelming). 

@d-wasserman - I will update the language using the text in quotes you provided

Expect the updated graphic either today or tomorrow--thanks again for the feedback!

**Comment by lianplass** [comment]
Updated~
![apa_planning_tech_repoflow-01](https://user-images.githubusercontent.com/54779774/120054647-18e29400-bfff-11eb-974e-dc0bd21c1d76.png)

**Comment by d-wasserman** [comment]
I like it. I think we can add this to the repo. 
I think we want to have it show up in the Contributing Section. We need to make a folder called "resources" to host the image. I don't think this will throw off the linter, but we should make the changes in a new branch to check. @lianplass , do want to take a first pass?

**Comment by lianplass** [comment]
@d-wasserman  sure thing.

**Comment by d-wasserman** [comment]
PR #23 addresses Contribution Scope. Going to close this issue for now.
